GOOGLE_API_CLIENT_ID: '754422472836-5cp5mtsdfkbrfefap93au6eriscgj9t0.apps.googleusercontent.com'
GOOGLE_API_CLIENT_SECRET: 'OfP8nw1w-ncXbxDj0YNqQMFP'
GOOGLE_API_KEY: 'AIzaSyCdF9s4n9ZhHbor8p4_hO0BnEIq_F2ZlSw'
